#!/bin/sh

current_time=$(TZ=UTC date +"%Y-%m-%dT%H:%M:%SZ")

for file in ./docs/*.md; do
  if ! git diff --cached --name-only --diff-filter=ACM --exit-code -- "$file" > /dev/null; then
    sed -i '' -e "s/updated_at: .*/updated_at: '$current_time'/" "$file"
    git add "$file"
  fi
done

exit 0
