services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:v7.2.0"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
      - source: hapi-extra-classes
        target: /app/extra-classes
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - ../data/hapi.postgres.data:/var/lib/postgresql/data

configs:
  hapi:
     file: ../configs/custom-interceptor.application.yaml
  hapi-extra-classes:
     file: ../my-interceptors/target
