services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:v7.2.0"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml

configs:
  hapi:
     file: ../configs/ig-jp-core-1.1.2.application.yaml
